# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 0) do

  create_table "anamnese", primary_key: "id_prontuario_anamnese", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_usuario"
    t.integer "id_paciente"
    t.datetime "data_anamnese"
    t.string "anm_estaTtoMedico"
    t.string "anm_motivoTto"
    t.string "anm_usaMedicamentos"
    t.text "anm_listMedicamentos"
    t.string "anm_procedimentoCirurgia"
    t.text "anm_qualProcCirurgia"
    t.string "anm_PA"
    t.string "anm_valorPA"
    t.string "anm_febreReumatica"
    t.string "anm_cardiovascular"
    t.string "anm_cardiovasculopatias"
    t.string "anm_asma"
    t.string "anm_difRespiracao"
    t.string "anm_hepatopatias"
    t.string "anm_DM"
    t.string "anm_artrite"
    t.string "anm_bisfosfonado"
    t.string "anm_gastro"
    t.string "anm_nefro"
    t.string "anm_soroHIV"
    t.string "anm_onco"
    t.string "anm_oncoTipo"
    t.string "anm_hemofilia"
    t.string "anm_gestante"
    t.string "anm_anemia"
    t.string "anm_usoDrogas"
    t.string "anm_usoDrogasTipo"
    t.string "anm_usoDrogasFreq"
    t.string "anm_usoAlcool"
    t.string "anm_usoAlcoolFreq"
    t.string "anm_usoTabaco"
    t.string "anm_usoTabacoTipo"
    t.string "anm_usoTabacoFreq"
    t.string "anm_alergiaMed"
    t.string "anm_alergiaTipoMed"
    t.string "anm_peso"
    t.string "anm_peso_2"
    t.string "anm_altura"
    t.string "anm_altura_2"
    t.text "anm_queixaPrincipal"
  end

  create_table "avaliacao", primary_key: "id_prontuario_avaliacao", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_usuario"
    t.integer "id_paciente"
    t.datetime "ava_data"
    t.string "ava_resp_att"
    t.string "ava_queixa_principal"
    t.string "ava_reg_afetada"
    t.string "ava_sintomas"
    t.string "ava_escala_dor"
    t.string "ava_sintomas_inicio"
    t.string "ava_sintomas_intensidade"
    t.string "ava_sintomas_localizacao"
    t.string "ava_sintomas_duracao"
    t.string "ava_sintomas_estimulo"
    t.string "ava_sintomas_tipo"
    t.string "ava_sintomas_fatEstimulantes"
    t.string "ava_sintomas_fatAtenuantes"
    t.string "ava_sintomas_associados"
    t.string "ava_histClinica_carie"
    t.string "ava_histClinica_traumatismo"
    t.string "ava_histClinica_tipoTrauma"
    t.string "ava_histClinica_periodoTrauma"
    t.string "ava_histClinica_ttoRealizados"
    t.string "ava_histClinica_tipoTto"
    t.string "ava_extraOral_edema"
    t.string "ava_extraOral_localEdema"
    t.string "ava_extraOral_linfoAde"
    t.string "ava_extraOral_localLinfoAde"
    t.string "ava_extraOral_dorPalpa"
    t.string "ava_extraOral_regiaoDor"
    t.string "ava_extraOral_fistula"
    t.string "ava_extraOral_localFistula"
    t.string "ava_intraOral_rastreamento"
    t.string "ava_intraOral_origemProcesso"
    t.string "ava_extraOral_outrasObs"
    t.string "ava_intraOral_coroa"
    t.string "ava_intraOral_material"
    t.string "ava_intraOral_adaptMarginal"
    t.string "ava_intraOral_material2"
    t.string "ava_intraOral_adaptMarginal2"
    t.string "ava_intraOral_outras"
    t.string "ava_intraOral_material3"
    t.string "ava_intraOral_inclinacaoDente"
    t.string "ava_intraOral_giroversao"
    t.string "ava_intrOral_BolsaPerio"
    t.string "ava_intraOral_faceBolsaPerio"
    t.string "ava_intraOral_faceBolsaPerioVestibular"
    t.string "ava_intraOral_faceBolsaPerioPalatina"
    t.string "ava_intraOral_faceBolsaPerioLingual"
    t.string "ava_intraOral_faceBolsaPerioMesial"
    t.string "ava_intraOral_faceBolsaPerioDistal"
    t.string "ava_intraOral_rastBolsaPerio"
    t.string "ava_intraOral_localBolsaPerio"
    t.string "ava_intraOral_NecrosePapilar"
    t.string "ava_intraOral_eritemaGengival"
    t.string "ava_IntraOral_InvEspacoBio"
    t.string "ava_intraOral_RetracaoGengival"
    t.string "ava_intraOral_hiperplasiaTec"
    t.string "ava_radio_AltPeriapical"
    t.string "ava_radio_IndicePeriapical"
    t.string "ava_radio_detalhes"
    t.string "ava_radio_detalhesTerco"
    t.string "ava_radio_detalhes1"
    t.string "ava_radio_detalhes2"
    t.string "ava_radio_detalhes3"
    t.string "ava_radio_detalhes4"
    t.string "ava_perdaOsseaRegLateral"
    t.string "ava_perdaOsseaRegLateralLocal"
    t.string "ava_perdaOsseaPerio"
    t.string "ava_tratamentoEndo"
    t.string "ava_tratamentoEndoSatTempo"
    t.string "ava_tratamentoEndoInsTempo"
    t.string "ava_caractApar"
    t.string "ava_caractApar1"
    t.string "ava_caractApar2"
    t.string "ava_caractApar3"
    t.string "ava_caractApar4"
    t.string "ava_caractApar5"
    t.string "ava_caractApar6"
    t.string "ava_caractAparCanaisNTrat"
    t.string "ava_caractAparConesPrata"
    t.string "ava_tomo"
    t.string "ava_tomoDetalhes"
    t.string "ava_diagnosticoPulpar"
    t.string "ava_diagnosticoPeriapical"
    t.string "ava_diagnosticoPeriodontal"
    t.string "ava_diagnosticoOutros"
    t.string "ava_diagnosticoObs"
    t.string "ava_tratamento"
    t.string "ava_tratamentoOutros"
  end

  create_table "controle", primary_key: "id_prontuario_controle", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_usuario"
    t.integer "id_paciente"
    t.datetime "con_data"
    t.string "pos_dente"
    t.string "pos_entrevista"
    t.string "pos_entrevistaTempo"
    t.string "pos_entrevistaOutro"
    t.string "pos_entrevistaObservacoes"
    t.string "pos_exameClinicoExtraOral"
    t.string "pos_edema"
    t.string "pos_edemaLocal"
    t.string "pos_edemaLocal2"
    t.string "pos_linfoadenopatia"
    t.string "pos_linfoadenopatiaLocal"
    t.string "pos_dorPalp"
    t.string "pos_dorPalpLocal"
    t.string "pos_fistula"
    t.string "pos_fistulaLocal"
    t.string "pos_exameClinicoObservacoes"
    t.string "pos_exameClinicoIntraOral"
    t.string "pos_coroa"
    t.string "pos_coroaMaterial"
    t.string "pos_coroaRestProv"
    t.string "pos_adaptMarg"
    t.string "pos_expCavPulp"
    t.string "pos_altCrom"
    t.string "pos_MobDental"
    t.string "pos_bolsaPerio"
    t.string "pos_bolsaPerioFace"
    t.string "pos_bolsaPerioFaceV"
    t.string "pos_bolsaPerioFaceP"
    t.string "pos_bolsaPerioFaceL"
    t.string "pos_bolsaPerioFaceM"
    t.string "pos_bolsaPerioFaceD"
    t.string "pos_bolsaPerioRast"
    t.string "pos_bolsaPerioRastLocal"
    t.string "pos_necrosepapilar"
    t.string "pos_eritemagengival"
    t.string "pos_retracaogengival"
    t.string "pos_ExIntEdema"
    t.string "pos_ExIntFistula"
    t.string "pos_ExIntFistulaRast"
    t.string "pos_ExIntFistulaRastOrigem"
    t.string "pos_ExIntFistulaRastOrigemPeriapice"
    t.string "pos_ExIntFistulaRastOrigemFurca"
    t.string "pos_ExIntFistulaRastOrigemPeriodonto"
    t.string "pos_ExIntHiperplasia"
    t.string "pos_ExIntAltOclusal"
    t.string "pos_SemiAux"
    t.string "pos_SemiAuxPercVert"
    t.string "pos_SemiAuxPercHoriz"
    t.string "pos_SemiAuxPercSom"
    t.string "pos_SemiAuxPercPressao"
    t.string "pos_SemiAuxPercDigitacao"
    t.string "pos_SemiAuxPercSensFrio"
    t.string "pos_SemiAuxPercCavidade"
    t.string "pos_SemiAuxPercAnestesia"
    t.string "pos_SemiAuxPercCalor"
    t.string "pos_Radio"
    t.string "pos_RadioAltPeriapical"
    t.string "pos_RadioAltPeriapicalDiametro"
    t.string "pos_RadioReabRad"
    t.string "pos_RadioObs"
    t.string "pos_RadioMedidasRadComprimento"
    t.string "pos_RadioMedidasRadEspessura"
    t.string "pos_RadioMedidasRadAbertura"
    t.string "pos_RadioMedidasRadBarreira"
    t.string "pos_encaminhamento"
    t.string "pos_encaminhamentodata"
    t.string "pos_encaminhamentooutro"
    t.string "pos_procedhoje"
  end

  create_table "curvatura_raizes", primary_key: "id_curvatura_raizes", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_examerx"
    t.string "coletado"
    t.string "raiz"
    t.string "curvatura"
  end

  create_table "esvaziamento_canais", primary_key: "id_ezv", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_tratamento"
    t.string "ezv_canal"
    t.string "ezv_procedimanto"
  end

  create_table "examerx", primary_key: "id_examerx", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_avaliacao"
    t.string "ava_exameRX"
    t.string "ava_exameRX_DataAnterior"
    t.string "ava_exameRX_dente"
    t.string "ava_exameRX_carie"
    t.string "ava_exameRX_tipo"
    t.string "ava_exameRX_coronaria"
    t.string "ava_exameRX_coronariaFace"
    t.string "ava_exameRX_CarieRadicular"
    t.string "ava_exameRX_CarieRadicularFace"
    t.string "ava_exameRX_matForrador"
    t.string "ava_exameRX_materialTipo"
    t.string "ava_exameRX_face"
    t.string "ava_exameRX_localizacaoDef"
    t.string "ava_exameRX_acessoEndo"
    t.string "ava_exameRX_coroaPilar"
    t.string "ava_exameRX_coroaPilarDef"
    t.string "ava_exameRX_tipoCoroaPilar"
    t.string "ava_exameRX_tracoFratura"
    t.string "ava_exameRX_fratura"
    t.string "ava_exameRX_tercoFratura"
    t.string "ava_exameRX_erosao"
    t.string "ava_exameRX_abrasao"
    t.string "ava_exameRX_atricao"
    t.string "ava_exameRX_HipoplasiaEsmalte"
    t.string "ava_exameRX_PerolaEsmalte"
    t.string "ava_exameRX_cuspideGarra"
    t.string "ava_exameRX_NodulosPulp"
    t.string "ava_exameRX_AtresiaCamPulpar"
    t.string "ava_exameRX_cinguloInvaginado"
    t.string "ava_exameRX_densInDente"
    t.string "ava_exameRX_braquetes"
    t.string "ava_exameRX_contencao"
    t.string "ava_exameRX_prepProtetico"
    t.string "ava_exameRX_localPrepProteticoLocalizacao"
    t.string "ava_exameRX_espacoPinoObturadorCanal"
    t.string "ava_exameRX_retentor"
    t.string "ava_exameRX_retentorCanal"
    t.string "ava_exameRX_apicetomia"
    t.string "ava_exameRX_matApicetomia"
    t.string "ava_exameRX_apicetomiaCanal"
    t.string "ava_exameRX_anquilose"
    t.string "ava_exameRX_tipoAnquilose"
    t.string "ava_exameRX_anquiloseRaiz"
    t.string "ava_exameRX_atresiaRadicular"
    t.string "ava_exameRX_tipoAtresiaRadicular"
    t.string "ava_exameRX_atresiaRadicularCanal"
    t.string "ava_exameRX_hipercementose"
    t.string "ava_exameRX_hipercementoseRaiz"
    t.string "ava_exameRX_agulhasCa"
    t.string "ava_exameRX_agulhasCaRaiz"
    t.string "ava_exameRX_areaReab"
    t.string "ava_exameRX_areaReabIntTerco"
    t.string "ava_exameRX_areaReabExtArea"
    t.string "ava_exameRX_areaReabComFace"
    t.string "ava_exameRX_apice"
    t.string "ava_exameRX_estagioNolla"
    t.string "ava_exameRX_medidas"
    t.string "ava_exameRX_medidasComprimento"
    t.string "ava_exameRX_medidasEspessura"
    t.string "ava_exameRX_medidasAbertura"
    t.string "ava_radio_AltPeriapical"
    t.string "ava_radio_IndicePeriapical"
    t.string "ava_radio_detalhes"
    t.string "ava_perdaOsseaRegLateral"
    t.string "ava_perdaOsseaRegLateralLocal"
    t.string "ava_perdaOsseaPerio"
    t.string "ava_tratamentoEndo"
    t.string "ava_tratamentoEndoSatTempo"
    t.string "ava_tratamentoEndoInsTempo"
    t.string "ava_caractApar"
    t.string "ava_caractApar1"
    t.string "ava_caractApar2"
    t.string "ava_caractApar3"
    t.string "ava_caractApar4"
    t.string "ava_caractApar5"
    t.string "ava_caractApar6"
    t.string "ava_caractAparCanaisNTrat"
    t.string "ava_caractAparConesPrata"
    t.string "raiz1"
    t.string "raiz2"
    t.string "raiz3"
    t.string "curvatura1"
    t.string "curvatura2"
    t.string "curvatura3"
  end

  create_table "obturacao", primary_key: "id_obt", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_tratamento"
    t.string "obt_canal"
    t.string "obt_tecnica"
    t.string "obt_tecnicaobs"
    t.string "obt_mat"
    t.string "obt_matobs"
    t.string "obt_matobs_n"
    t.string "obt_cimento"
    t.string "obt_cimentoobs"
  end

  create_table "odontometria", primary_key: "id_odo", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_tratamento"
    t.string "odo_canal"
    t.string "odo_ref_clinica"
    t.string "odo_cad"
    t.string "odo_cri"
    t.string "odo_crd"
    t.string "odo_ct"
  end

  create_table "paciente", primary_key: "id_paciente", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.string "paciente_nome"
    t.date "paciente_nascimento"
    t.string "paciente_sexo"
    t.string "paciente_endereco"
    t.string "paciente_telefone"
    t.string "paciente_email"
    t.string "paciente_rg"
    t.string "paciente_cpf"
    t.string "paciente_acompanhante"
    t.date "paciente_datacadastro"
  end

  create_table "pqm", primary_key: "id_pqm", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_tratamento"
    t.string "pqm_canal"
    t.string "pqm_tecnicamanual"
    t.string "pqm_tecnicamanual1"
    t.string "pqm_tecnicamanualoutro"
    t.string "pqm_tecnicaautomatizada"
    t.string "pqm_tecnicaautomatizada1"
    t.string "pqm_tecnicaautomatizadaoutro"
    t.string "pqm_instrumentosmanuais"
    t.string "pqm_instrumentosmanuaisoutro"
    t.string "pqm_instrumentosmotor"
    t.string "pqm_instrumentosmotoroutro"
    t.string "pqm_instrumentosdiainicial"
    t.string "pqm_instrumentosdiainicial_n"
    t.string "pqm_instrumentosdiafinal"
    t.string "pqm_instrumentosdiafinal_n"
    t.string "pqm_instrumentosdiaobs"
    t.string "pqm_etapa"
    t.string "pqm_etapa_n"
  end

  create_table "prep_terco_cervical", primary_key: "id_prep", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_tratamento"
    t.string "prep_canal"
    t.string "prep_largo"
    t.string "prep_gatesglidden"
    t.string "prep_laaxxes"
    t.string "prep_outra"
    t.string "prep_numero"
  end

  create_table "semioaux", primary_key: "id_semioAux", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.integer "id_prontuario_avaliacao"
    t.string "ava_semioAux_dente"
    t.string "ava_semioAux_percVertical"
    t.string "ava_semioAux_percHorizontal"
    t.string "ava_semioAux_somMetalPerc"
    t.string "ava_semioAux_pressaoApical"
    t.string "ava_semioAux_sensivelFrio"
    t.string "ava_semioAux_testeCavidade"
    t.string "ava_semioAux_testeAnestesio"
    t.string "ava_semioAux_calor"
  end

  create_table "tratamento", primary_key: "id_prontuario_tratamento", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci" do |t|
    t.integer "id_usuario"
    t.integer "id_paciente"
    t.datetime "data_tratamento"
    t.string "dente"
    t.string "magnificacao", collation: "latin1_swedish_ci"
    t.string "anestesia", collation: "latin1_swedish_ci"
    t.string "tecnica_anestesica"
    t.string "anestesico"
    t.string "isolamento", collation: "latin1_swedish_ci"
    t.string "isolamento_absoluto", collation: "latin1_swedish_ci"
    t.string "acesso_canais", collation: "latin1_swedish_ci"
    t.string "odo_naocoletado", collation: "latin1_swedish_ci"
    t.string "ezv_naocoletado", collation: "latin1_swedish_ci"
    t.string "prep_naocoletado", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_1", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_2", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_2obs", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_3", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_4", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_4obs", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_5", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_5obs", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_6", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_7", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_8", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_9", collation: "latin1_swedish_ci"
    t.string "prep_auxquim_9obs", collation: "latin1_swedish_ci"
    t.string "pqm_naocoletado", collation: "latin1_swedish_ci"
    t.string "pqm_medint_1", collation: "latin1_swedish_ci"
    t.string "pqm_medint_2", collation: "latin1_swedish_ci"
    t.string "pqm_medint_3", collation: "latin1_swedish_ci"
    t.string "pqm_medint_4", collation: "latin1_swedish_ci"
    t.string "pqm_medint_4obs", collation: "latin1_swedish_ci"
    t.string "pqm_medint_5", collation: "latin1_swedish_ci"
    t.string "pqm_medint_6", collation: "latin1_swedish_ci"
    t.string "pqm_medint_7", collation: "latin1_swedish_ci"
    t.string "pqm_medint_8", collation: "latin1_swedish_ci"
    t.string "pqm_medint_9", collation: "latin1_swedish_ci"
    t.string "pqm_medint_10", collation: "latin1_swedish_ci"
    t.string "pqm_medint_11", collation: "latin1_swedish_ci"
    t.string "pqm_medint_12", collation: "latin1_swedish_ci"
    t.string "pqm_ind_coa", collation: "latin1_swedish_ci"
    t.string "pqm_ind_coaobs", collation: "latin1_swedish_ci"
    t.string "pqm_protcerv", collation: "latin1_swedish_ci"
    t.string "pqm_protcervobs", collation: "latin1_swedish_ci"
    t.string "obt_naocoletado", collation: "latin1_swedish_ci"
    t.string "pre_mednaocoletado", collation: "latin1_swedish_ci"
    t.string "pre_med1", collation: "latin1_swedish_ci"
    t.string "pre_med1obs", collation: "latin1_swedish_ci"
    t.string "pre_med2", collation: "latin1_swedish_ci"
    t.string "pre_med2obs", collation: "latin1_swedish_ci"
    t.string "pre_med3", collation: "latin1_swedish_ci"
    t.string "pre_med3obs", collation: "latin1_swedish_ci"
    t.string "pre_med4", collation: "latin1_swedish_ci"
    t.string "pre_med4obs", collation: "latin1_swedish_ci"
    t.string "interc_naocoletado", collation: "latin1_swedish_ci"
    t.string "interc_1", collation: "latin1_swedish_ci"
    t.string "interc_2", collation: "latin1_swedish_ci"
    t.string "interc_3", collation: "latin1_swedish_ci"
    t.string "tinterc_naocoletado", collation: "latin1_swedish_ci"
    t.string "tinterc_1", collation: "latin1_swedish_ci"
    t.string "tinterc_2", collation: "latin1_swedish_ci"
    t.string "tinterc_3", collation: "latin1_swedish_ci"
    t.string "tinterc_4", collation: "latin1_swedish_ci"
    t.string "tinterc_5", collation: "latin1_swedish_ci"
    t.string "tinterc_6", collation: "latin1_swedish_ci"
    t.string "tinterc_7", collation: "latin1_swedish_ci"
    t.string "tinterc_7obs", collation: "latin1_swedish_ci"
    t.string "tinterc_8", collation: "latin1_swedish_ci"
    t.string "tinterc_8obs", collation: "latin1_swedish_ci"
    t.string "minterc_naocoletado", collation: "latin1_swedish_ci"
    t.string "minterc_1", collation: "latin1_swedish_ci"
    t.string "minterc_2", collation: "latin1_swedish_ci"
    t.string "minterc_3", collation: "latin1_swedish_ci"
    t.string "minterc_4", collation: "latin1_swedish_ci"
    t.string "minterc_5", collation: "latin1_swedish_ci"
    t.string "minterc_6", collation: "latin1_swedish_ci"
    t.string "minterc_7", collation: "latin1_swedish_ci"
    t.string "minterc_8", collation: "latin1_swedish_ci"
    t.string "minterc_9", collation: "latin1_swedish_ci"
    t.string "minterc_10", collation: "latin1_swedish_ci"
    t.string "minterc_11", collation: "latin1_swedish_ci"
    t.string "minterc_12", collation: "latin1_swedish_ci"
    t.string "minterc_13", collation: "latin1_swedish_ci"
    t.string "minterc_13obs", collation: "latin1_swedish_ci"
    t.string "minterc_obs", collation: "latin1_swedish_ci"
    t.string "acidentes_naocoletado", collation: "latin1_swedish_ci"
    t.string "acidentes_1", collation: "latin1_swedish_ci"
    t.string "acidentes_2", collation: "latin1_swedish_ci"
    t.string "acidentes_3", collation: "latin1_swedish_ci"
    t.string "tacidentes_naocoletado", collation: "latin1_swedish_ci"
    t.string "tacidentes_1", collation: "latin1_swedish_ci"
    t.string "tacidentes_1obs", collation: "latin1_swedish_ci"
    t.string "tacidentes_1obs2", collation: "latin1_swedish_ci"
    t.string "tacidentes_2", collation: "latin1_swedish_ci"
    t.string "tacidentes_3", collation: "latin1_swedish_ci"
    t.string "tacidentes_4", collation: "latin1_swedish_ci"
    t.string "tacidentes_5", collation: "latin1_swedish_ci"
    t.string "tacidentes_6", collation: "latin1_swedish_ci"
    t.string "tacidentes_7", collation: "latin1_swedish_ci"
    t.string "tacidentes_8", collation: "latin1_swedish_ci"
    t.string "tacidentes_9", collation: "latin1_swedish_ci"
    t.string "tacidentes_ext", collation: "latin1_swedish_ci"
    t.string "tacidentes_10", collation: "latin1_swedish_ci"
    t.string "tacidentes_11", collation: "latin1_swedish_ci"
    t.string "tacidentes_12", collation: "latin1_swedish_ci"
    t.string "tacidentes_13", collation: "latin1_swedish_ci"
    t.string "tacidentes_14", collation: "latin1_swedish_ci"
    t.string "tacidentes_tinst", collation: "latin1_swedish_ci"
    t.string "tacidentes_15", collation: "latin1_swedish_ci"
    t.string "tacidentes_16", collation: "latin1_swedish_ci"
    t.string "tacidentes_17", collation: "latin1_swedish_ci"
    t.string "tacidentes_18", collation: "latin1_swedish_ci"
    t.string "tacidentes_19", collation: "latin1_swedish_ci"
    t.string "tacidentes_20", collation: "latin1_swedish_ci"
    t.string "tacidentes_21", collation: "latin1_swedish_ci"
    t.string "tacidentes_22", collation: "latin1_swedish_ci"
    t.string "tacidentes_22obs", collation: "latin1_swedish_ci"
    t.string "macidentes_naocoletado", collation: "latin1_swedish_ci"
    t.string "macidentes_1", collation: "latin1_swedish_ci"
    t.string "macidentes_2", collation: "latin1_swedish_ci"
    t.string "macidentes_3", collation: "latin1_swedish_ci"
    t.string "macidentes_4", collation: "latin1_swedish_ci"
    t.string "macidentes_5", collation: "latin1_swedish_ci"
    t.string "macidentes_6", collation: "latin1_swedish_ci"
    t.string "macidentes_7", collation: "latin1_swedish_ci"
    t.string "macidentes_7obs", collation: "latin1_swedish_ci"
    t.string "macidentes_8", collation: "latin1_swedish_ci"
    t.string "macidentes_9", collation: "latin1_swedish_ci"
    t.string "macidentes_10", collation: "latin1_swedish_ci"
    t.string "macidentes_10obs", collation: "latin1_swedish_ci"
    t.string "macidentes_11", collation: "latin1_swedish_ci"
    t.string "macidentes_12", collation: "latin1_swedish_ci"
    t.string "macidentes_13", collation: "latin1_swedish_ci"
    t.string "macidentes_14", collation: "latin1_swedish_ci"
    t.string "macidentes_15", collation: "latin1_swedish_ci"
    t.string "macidentes_16", collation: "latin1_swedish_ci"
    t.string "macidentes_17", collation: "latin1_swedish_ci"
    t.string "macidentes_18", collation: "latin1_swedish_ci"
    t.string "macidentes_19", collation: "latin1_swedish_ci"
    t.string "macidentes_20", collation: "latin1_swedish_ci"
    t.string "macidentes_21", collation: "latin1_swedish_ci"
    t.string "macidentes_22", collation: "latin1_swedish_ci"
    t.string "macidentes_23", collation: "latin1_swedish_ci"
    t.string "macidentes_24", collation: "latin1_swedish_ci"
    t.string "macidentes_25", collation: "latin1_swedish_ci"
    t.string "macidentes_26", collation: "latin1_swedish_ci"
    t.string "macidentes_27", collation: "latin1_swedish_ci"
    t.string "macidentes_28", collation: "latin1_swedish_ci"
    t.string "macidentes_28obs", collation: "latin1_swedish_ci"
    t.string "macidentes_29", collation: "latin1_swedish_ci"
    t.string "macidentes_30", collation: "latin1_swedish_ci"
    t.string "macidentes_31", collation: "latin1_swedish_ci"
    t.string "macidentes_32", collation: "latin1_swedish_ci"
    t.string "macidentes_33", collation: "latin1_swedish_ci"
    t.string "macidentes_34", collation: "latin1_swedish_ci"
    t.string "macidentes_35", collation: "latin1_swedish_ci"
    t.string "macidentes_36", collation: "latin1_swedish_ci"
    t.string "macidentes_37", collation: "latin1_swedish_ci"
    t.string "macidentes_38", collation: "latin1_swedish_ci"
    t.string "macidentes_38obs", collation: "latin1_swedish_ci"
    t.string "macidentes_39", collation: "latin1_swedish_ci"
    t.string "macidentes_obs", collation: "latin1_swedish_ci"
  end

  create_table "usuario", primary_key: "id_usuario", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=latin1" do |t|
    t.string "email"
    t.string "senha"
    t.string "nome"
    t.string "instituicao"
    t.string "setor"
    t.string "cargo"
  end

end
